apiVersion: v1
kind: Pod
metadata:
  name: configmap-test
  labels:
    app: configmap-test
spec:
  containers:
    - name: test-container
      image: nginx
      ports:
        - name: http-server
          containerPort: 80
      volumeMounts:
      - name: config-volume
        mountPath: /usr/share/nginx/html
  volumes:
    - name: config-volume
      configMap:
        name: tal-cm
